import "./reset.css";
import "./globals.css";
import { Krub, Rubik } from "next/font/google";
import Header from "@/components/header";

const rubik = Rubik({ subsets: ["latin"] });
export const krub = Krub({subsets: ["latin"], weight: ['200','300','400']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
